server:
  port: 8080
  contextPath: ${spring.application.name}
  servlet:
    context-path: ${spring.application.name}
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: /api
  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5432/demoApi
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: false

url:
  service:
    flights: http://localhost:6070/api/flights/catalog/city/{code}

http-connector:
  hosts:
    api-catalog:
      host: http://localhost
      port: 6070
      endpoints:
        get-city:
          url: "/api/flights/catalog/city/{code}"
          readTimeout: 1000
          writeTimeout: 1000
          connectionTimeout: 1000

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
# Permite cambiar el path
#      path-mapping:
#        health: healthcheck

logging:
  level:
    org:
      springframework:
        boot:
          actuate:
            health: DEBUG
            endpoint:
              web:
                servlet:
                  WebMvcEndpointHandlerMapping: TRACE


# Configuración de la información personalizada con la versión desde el pom.xml
info:
  app:
    name: @project.name@
    version: @project.version@
    description: @project.description@